# =============================================
#  CART-SERVICE Configuration
# =============================================

# Port du serveur (different du product-service)
server.port=8082

# Nom de l'application (utilise par Eureka)
spring.application.name=cart-service

# =============================================
#  H2 In-Memory Database (base SEPAREE !)
# =============================================
spring.datasource.url=jdbc:h2:mem:cartdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2 (http://localhost:8082/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =============================================
#  ActiveMQ
# =============================================
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

# =============================================
#  Eureka Client
# =============================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# =============================================
#  Actuator
# =============================================
management.endpoints.web.exposure.include=health,info
